const sqlite3 = require('sqlite3').verbose();

// Connect to the SQLite database
const db = new sqlite3.Database('./shopperAppDatabase.db');

const products = [
    { name: "Men Slim Fit Bomber Jacket", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.", price: 700, stock: 10, category: "men", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725364046/-473Wx593H-465324816-tan-MODEL_t1pfiw.jpg" },
    { name: "Men Slim Fit Bomber Jacket", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.", price: 400, stock: 1, category: "men", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725364045/Finisterre_20fourier_20jacket_yleiig.jpg" },
    { name: "Men Slim Fit Bomber Jacket", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.", price: 650, stock: 6, category: "men", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725364045/61eMJalktNL._AC_UY1100__atlnbm.jpg" },
    { name: "Men Slim Fit Bomber Jacket", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.", price: 800, stock: 6, category: "men", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725364044/fc12c679-7297-4038-b25e-65c0c396583d1713177218259-Roadster-Men-Jackets-7011713177217619-1_pyrtid.jpg" },
    { name: "Men Slim Fit Bomber Jacket", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.", price: 770, stock: 9, category: "men", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725364044/GMW23-002038019242_1_vyv1ni.jpg" },
   
    { name: "Men Slim Fit Bomber Jacket", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.", price: 590, stock: 2, category: "men", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725364043/1024x1024-Mens-Keanu-Black-010924-1_arw0zt.jpg" },
    { name: "Men Slim Fit Bomber Jacket", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.", price: 886, stock: 5, category: "men", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725364043/men-s-winter-fashion-jacket-500x500_pbxumn.jpg" },
    { name: "Men Slim Fit Bomber Jacket", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.", price: 476, stock: 6, category: "men", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725364042/71VFs2XrDVL._AC_UY350__xzpv0i.jpg" },
    { name: "Men Slim Fit Bomber Jacket", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.", price: 985, stock: 3, category: "men", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725364042/m-no-multicolor-part-1-jammyandkammo-original-imags47ppjxrsg9n_eeqwmp.jpg" },
    { name: "Men Slim Fit Bomber Jacket", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.", price: 576, stock: 9, category: "men", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725364046/-473Wx593H-465324816-tan-MODEL_t1pfiw.jpg" },
    
    { name: "Men Slim Fit Bomber Jacket", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.", price: 722, stock: 5, category: "men", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725364042/s-mnt-7019-montrez-original-imag5hb9s6wnr9vy-bb_rwtcef.jpg" },
    { name: "Men Slim Fit Bomber Jacket", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.", price: 721, stock: 6, category: "men", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725364041/055181_nav_manta_borg_lined_padded_jacket_men_ecom_lifestyle_aw23_01_ri7s1e.jpg" },
    { name: "Men Slim Fit Bomber Jacket", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.", price: 700, stock: 8, category: "men", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725364041/m6078_red-bridge-men-jacket-biker-jacket-leather-jacket-brando-real-leather-m6078_5_cpeeuq.jpg" },
    { name: "Men Slim Fit Bomber Jacket", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.", price: 689, stock: 3, category: "men", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725364041/s-l400_p5zl4v.jpg" },
    { name: "Men Slim Fit Bomber Jacket", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.", price: 983, stock: 7, category: "men", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725364040/eng_pl_Mens-Denim-Jacket-Navy-Blue-Bolf-200A-92820_2_u6h64l.jpg" },
    
    { name: "Men Slim Fit Bomber Jacket", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.", price: 734, stock: 17, category: "men", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725364039/LEEy-world-Flannel-Jackets-for-Men-Men-s-Winter-Coats-Water-Repellent-Windproof-Thicken-Parkas-Long-Hooded-Padded-Puffer-Jacket-Army-Green-3XL_ac45c466-ef90-489f-9706-175f267a3a5c.470850f9ef1e19a0b933aa2e3160afd9_kyurhi.jpg" },
    { name: "Men Slim Fit Bomber Jacket", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.", price: 856, stock: 11, category: "men", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725364039/2302-ICM-JKT6598_2_xnrkvu.jpg" },
    { name: "Men Slim Fit Bomber Jacket", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.", price: 976, stock: 10, category: "men", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725364038/71ZSywHMLLL._AC_UY1000__a284cm.jpg" },
    { name: "Men Slim Fit Bomber Jacket", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.", price: 1670, stock: 10, category: "men", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725364037/s-l1200_oskbhs.jpg" },
    { name: "Men Slim Fit Bomber Jacket", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.", price: 766, stock: 14, category: "men", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725364037/-473Wx593H-469518400-olive-MODEL_hikebm.jpg" },
    
    { name: "Men Slim Fit Bomber Jacket", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.", price: 500, stock: 8, category: "men", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725364037/monte-baldo-winter-jacket-men-grey-model_ugucjy.jpg" },
    { name: "Men Slim Fit Bomber Jacket", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.", price: 670, stock: 9, category: "men", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725364036/960x0_xfgmxe.jpg" },
    { name: "Men Slim Fit Bomber Jacket", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.", price: 600, stock: 5, category: "men", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725364036/51ylk6F0rfL._AC_SL1000__e233fu.jpg" },
    { name: "Men Slim Fit Bomber Jacket", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.", price: 900, stock: 5, category: "men", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725364036/Mens-Bomber-Jackets-1582970719331_l4r2vs.webp" },
    { name: "Men Slim Fit Bomber Jacket", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.", price: 400, stock: 4, category: "men", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725364035/Men-Leather-Jackets-1582970628214_figkx2.webp" },
    


    { name: "Women Slim Fit Jacket", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment." , price: 400, stock: 4, category: "Women", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725364544/product_5_f7ukso.png" },
    { name: "Women Slim Fit Jacket", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment." , price: 700, stock: 5, category: "Women", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725364543/product_9_stn5ya.png" },
    { name: "Women Slim Fit Jacket", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment." , price: 478, stock: 7, category: "Women", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725364541/product_6_b0apuf.png" },
    { name: "Women Slim Fit Jacket", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment." , price: 890, stock: 8, category: "Women", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725364540/product_12_hgpfgs.png" },
    { name: "Women Slim Fit Jacket", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment." , price: 560, stock: 22, category: "Women", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725364538/product_11_ub0stu.png" },
    
    { name: "Women Slim Fit Jacket", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment." , price: 676, stock: 15, category: "Women", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725364536/product_10_zcq4mw.png" },
    { name: "Women Slim Fit Jacket", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment." , price: 679, stock: 20, category: "Women", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725364533/product_4_aivwtw.png" },
    { name: "Women Slim Fit Jacket", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment." , price: 800, stock: 14, category: "Women", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725364526/product_1_j99gs3.png" },
    { name: "Women Slim Fit Jacket", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment." , price: 500, stock: 24, category: "Women", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725364472/product_8_qvdfxh.png" },
    { name: "Women Slim Fit Jacket", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment." , price: 605, stock: 8, category: "Women", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725364467/product_7_dcgj6h.png" },
    
    { name: "Women Slim Fit Jacket", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment." , price: 570, stock: 8, category: "Women", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725364408/zoom_0-1675318564_v0yzpt.jpg" },
    { name: "Women Slim Fit Jacket", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment." , price: 666, stock: 5, category: "Women", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725364408/l-1-no-ef-jkt-sea-green-l-ellipse-original-imaggcq6g4tgbpvz_b6py1n.jpg" },
    { name: "Women Slim Fit Jacket", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment." , price: 670, stock: 7, category: "Women", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725364406/l-no-oa-0005-carrot-m-ellipse-original-imagpfpz9hrvvddq_ufphmj.jpg" },
    { name: "Women Slim Fit Jacket", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment." , price: 986, stock: 2, category: "Women", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725364406/s-no-slc-women-winter-jackets-slc-original-imags224djwfzesg_uwtcnp.jpg" },
    { name: "Women Slim Fit Jacket", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment." , price: 548, stock: 1, category: "Women", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725364308/2302-ICW-JKT6610_2_mgu09z.jpg" },
    
    { name: "Women Slim Fit Jacket", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment." , price: 500, stock: 3, category: "Women", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725364269/GUEST_9d868e26-4c95-4fc0-ba60-0d5f729f072c_oxlngx.jpg" },
    { name: "Women Slim Fit Jacket", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment." , price: 454, stock: 9, category: "Women", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725364268/febc7e90fbc4353cad4f9e467cbbe28d_cdhxez.jpg" },
    { name: "Women Slim Fit Jacket", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment." , price: 754, stock: 10, category: "Women", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725364268/Qiaocaity-Womens-Fall-Fashion-Long-Trench-Coat-2022-Womens-Lapel-Woolen-Cloth-Coat-Trench-Jacket-Long-Overcoat-Outerwear-Cardigan-Khaki-XL_2e8bee51-26e4-4636-a67e-c051fdf440cc.795552c5de9e16d043ef436200058cf7_sslclr.jpg" },
    { name: "Women Slim Fit Jacket", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment." , price: 568, stock: 11, category: "Women", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725364267/Faux-Leather-Jacket-Women-Plus-Size-Cool-Faux-Leather-Jacket-Long-Sleeve-Zipper-Fitted-Coat-Fall-Short-Jacket-Reduced-Price-and-Promotions_3f48ed63-3e71-41cc-94eb-68422fe012ff.960a6b5712dd911226cddcce9a4384e2_pnppgg.jpg" },
    { name: "Women Slim Fit Jacket", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment." , price: 863, stock: 7, category: "Women", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725364266/1_kltz5q.jpg" },
    
    { name: "Women Slim Fit Jacket", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment." , price: 863, stock: 13, category: "Women", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725364266/1_rggg9i.jpg" },
    { name: "Women Slim Fit Jacket", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment." , price: 600, stock: 17, category: "Women", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725364265/cn52755033_udndxz.jpg" },
    { name: "Women Slim Fit Jacket", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment." , price: 380, stock: 19, category: "Women", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725364265/victoria-leather-jacket-open_ewee1x.jpg" },
    { name: "Women Slim Fit Jacket", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment." , price: 499, stock: 5, category: "Women", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725364264/s-l1200_kppitr.jpg" },
    { name: "Women Slim Fit Jacket", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment." , price: 645, stock: 3, category: "Women", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725364172/l-lw-9102-b-tilton-original-imagjup95gdv5cec_v6yw7e.jpg" },
    
    { name: "Women Slim Fit Jacket", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment." , price: 666, stock: 5, category: "Women", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725364172/m-473-sanwariya-creation-original-imaggzkrwd6zdu78_awncbz.jpg" },
    { name: "Women Slim Fit Jacket", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment." , price: 670, stock: 7, category: "Women", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725364173/kk25-11-230463copyfinal_1_1024x_c7tbr5.jpg" },
    { name: "Women Slim Fit Jacket", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment." , price: 986, stock: 2, category: "Women", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725364172/springlovemin_3_xu8xbk.jpg" },
    { name: "Women Slim Fit Jacket", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment." , price: 548, stock: 1, category: "Women", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725364172/buynewtrend-light-blue-georgette-floral-print-smocked-women-midi-dress-product-images-rvavpevp1g-0-202303041931_sri1z7.webp" },
   
    

    { name: "Hooded Sweatshirt", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment." , price: 367, stock: 5, category: "Kid", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725372385/product_36_i39d5m.png" },
    { name: "Hooded Sweatshirt", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment." , price: 546, stock: 3, category: "Kid", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725372383/product_35_xfybcq.png" },
    { name: "Hooded Sweatshirt", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment." , price: 440, stock: 2, category: "Kid", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725372382/product_34_znnyjk.png" },
    { name: "Hooded Sweatshirt", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment." , price: 399, stock: 6, category: "Kid", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725372382/product_31_u4pckn.png" },
    { name: "Hooded Sweatshirt", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment." , price: 374, stock: 7, category: "Kid", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725372380/product_30_dsiiao.png" },
    
    { name: "Hooded Sweatshirt", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment." , price: 420, stock: 9, category: "Kid", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725372378/product_28_yjpelk.png" },
    { name: "Hooded Sweatshirt", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment." , price: 480, stock: 10, category: "Kid", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725372378/product_29_r93pj2.png" },
    { name: "Hooded Sweatshirt", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment." , price: 567, stock: 12, category: "Kid", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725372380/product_30_dsiiao.png" },
    { name: "Hooded Sweatshirt", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment." , price: 644, stock: 13, category: "Kid", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725372344/product_27_tnssns.png" },
    { name: "Hooded Sweatshirt", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment." , price: 477, stock: 1, category: "Kid", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725372345/product_32_fdpdhl.png" },
    
    { name: "Hooded Sweatshirt", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment." , price: 555, stock: 16, category: "Kid", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725372343/product_26_q0gath.png" },
    { name: "Hooded Sweatshirt", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment." , price: 345, stock: 18, category: "Kid", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725372303/-473Wx593H-463465237-maroon-MODEL_b9pvsn.jpg" },
    { name: "Hooded Sweatshirt", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment." , price: 434, stock: 4, category: "Kid", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725372301/6558b5da86ad202ca74816b2-kids-boys-classic-suit-coat-formal_debrac.jpg" },
    { name: "Hooded Sweatshirt", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment." , price: 435, stock: 6, category: "Kid", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725372297/kids-boy-jacket-1565766769-5043645_bm3nmh.jpg" },
    { name: "Hooded Sweatshirt", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment." , price: 561, stock: 17, category: "Kid", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725372296/2023-OEM-Trendy-Kids-Clothing-Cotton-Formal-Custom-Boys-Suit-Kids-Suit-Jacket-Pants_jftdwa.webp" },
    
    { name: "Hooded Sweatshirt", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment." , price: 456, stock: 8, category: "Kid", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725372296/2023-OEM-Trendy-Kids-Clothing-Cotton-Formal-Custom-Boys-Suit-Kids-Suit-Jacket-Pants_jftdwa.webp" },
    { name: "Hooded Sweatshirt", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment." , price: 612, stock: 18, category: "Kid", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725372065/0cf6b41350371a1ae949009989f8f65f_modqoz.jpg" },
    { name: "Hooded Sweatshirt", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment." , price: 462, stock: 16, category: "Kid", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725372064/kids-hooded-jacket-500x500_p4h5tn.jpg" },
    { name: "Hooded Sweatshirt", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment." , price: 532, stock: 17, category: "Kid", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725372062/product-jpeg-500x500_k9zpmo.jpg" },
    { name: "Hooded Sweatshirt", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment." , price: 365, stock: 15, category: "Kid", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725372061/WWIILeatherLookKidsJacket_1024x1024_sbbuxk.jpg" },
    
    { name: "Hooded Sweatshirt", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment." , price: 621, stock: 15, category: "Kid", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725371988/s-l400_dfmrdn.jpg" },
    { name: "Hooded Sweatshirt", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment." , price: 415, stock: 7, category: "Kid", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725371987/hand-block-printed-pure-chanderi-silk-nehru-jacket-in-yellow-v1-ung44_qj5qkz.jpg" },
    { name: "Hooded Sweatshirt", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment." , price: 423, stock: 4, category: "Kid", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725371986/s-l400_vzsiqx.jpg" },
    { name: "Hooded Sweatshirt", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment." , price: 512, stock: 1, category: "Kid", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725371983/s-l400_ssx0z9.jpg" },
    { name: "Hooded Sweatshirt", description: "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment." , price: 366, stock: 19, category: "Kid", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725371981/61V2pBnVwVS._AC_UY1000__trjlme.jpg" },
    
    
    { name: "girl glorious dress for occasional wear ", description: "A lightweight, usually knitted, pullover dress, close-fitting and with a round neckline and short sleeves, worn as outer garment." , price: 366, stock: 11, category: "Kid", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725371927/Kids-Girl-Party-Wear-Western-Floral-Flower-Girl-Dress_k6pd25.webp" },
    { name: "girl glorious dress for occasional wear ", description: "A lightweight, usually knitted, pullover dress, close-fitting and with a round neckline and short sleeves, worn as outer garment." , price: 455, stock: 12, category: "Kid", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725371926/d201af94ac8a491d3388458e0664ef3f_a1cwbl.jpg" },
    { name: "girl glorious dress for occasional wear ", description: "A lightweight, usually knitted, pullover dress, close-fitting and with a round neckline and short sleeves, worn as outer garment." , price: 578, stock: 1, category: "Kid", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725371922/babyvasudevimin_4_mcmr0l.jpg" },
    { name: "girl glorious dress for occasional wear ", description: "A lightweight, usually knitted, pullover dress, close-fitting and with a round neckline and short sleeves, worn as outer garment." , price: 555, stock: 9, category: "Kid", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725371920/H94991bdc3cb5491daa3c6fb2a699a6a8Z.jpg_720x720q50_x1h6qv.webp" },
    { name: "girl glorious dress for occasional wear ", description: "A lightweight, usually knitted, pullover dress, close-fitting and with a round neckline and short sleeves, worn as outer garment." , price: 400, stock: 9, category: "Kid", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725371916/LashkaraDay325-01-241637_t2r4nx.jpg" },
    
    { name: "girl glorious dress for occasional wear ", description: "A lightweight, usually knitted, pullover dress, close-fitting and with a round neckline and short sleeves, worn as outer garment." , price: 456, stock: 4, category: "Kid", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725371915/f2f2d1a2c371245ca61a6214a6020bfd_g2tonj.jpg" },
    { name: "girl glorious dress for occasional wear ", description: "A lightweight, usually knitted, pullover dress, close-fitting and with a round neckline and short sleeves, worn as outer garment." , price: 500, stock: 3, category: "Kid", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725371914/Purple6_wkqy3w.jpg" },
    { name: "girl glorious dress for occasional wear ", description: "A lightweight, usually knitted, pullover dress, close-fitting and with a round neckline and short sleeves, worn as outer garment." , price: 300, stock: 5, category: "Kid", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725371911/Lovely-Kids-Party-Wear-Elegant-Baby-Clothing-Clothes-Dots-Smocked-Wedding-Little-Girl-Dress_k03p06.webp" },
    { name: "girl glorious dress for occasional wear ", description: "A lightweight, usually knitted, pullover dress, close-fitting and with a round neckline and short sleeves, worn as outer garment." , price: 357, stock: 7, category: "Kid", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725371910/peach-satin-dhoti-delight-party-wear-dress-for-girls-lagorii-kids-1_lju0da.jpg" },
    { name: "girl glorious dress for occasional wear ", description: "A lightweight, usually knitted, pullover dress, close-fitting and with a round neckline and short sleeves, worn as outer garment." , price: 366, stock: 8, category: "Kid", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725371910/618acc1e80dab90018db0144_pgllaa.jpg" },
    
    { name: "girl glorious dress for occasional wear ", description: "A lightweight, usually knitted, pullover dress, close-fitting and with a round neckline and short sleeves, worn as outer garment." , price: 376, stock: 10, category: "Kid", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725371833/hmgoepprod_ozkifr.jpg" },
    { name: "girl glorious dress for occasional wear ", description: "A lightweight, usually knitted, pullover dress, close-fitting and with a round neckline and short sleeves, worn as outer garment." , price: 386, stock: 1, category: "Kid", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725371833/67085996_23_wxqxbu.jpg" },
    { name: "girl glorious dress for occasional wear ", description: "A lightweight, usually knitted, pullover dress, close-fitting and with a round neckline and short sleeves, worn as outer garment." , price: 466, stock: 12, category: "Kid", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725371830/2a9b72b9-1d75-43fa-a7a7-19a40b1d4474.3b061d4bffa4645153607a863f04c017_fbniur.jpg" },
    { name: "girl glorious dress for occasional wear ", description: "A lightweight, usually knitted, pullover dress, close-fitting and with a round neckline and short sleeves, worn as outer garment." , price: 496, stock: 13, category: "Kid", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725371829/31d55709-e5fb-4b8e-a3a8-ffe4cd9d9dbb.e94c3a5be43e274ac695097153855add_rizhuf.jpg" },
    { name: "girl glorious dress for occasional wear ", description: "A lightweight, usually knitted, pullover dress, close-fitting and with a round neckline and short sleeves, worn as outer garment." , price: 366, stock: 5, category: "Kid", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725371828/218e3f96a994a871349c39bca7b9a132_qsqrjj.jpg" },
    
    { name: "girl glorious dress for occasional wear ", description: "A lightweight, usually knitted, pullover dress, close-fitting and with a round neckline and short sleeves, worn as outer garment." , price: 573, stock: 15, category: "Kid", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725371724/2f023d6ea14cac096078933b3b3b2a6c_uq62qe.jpg" },
    { name: "girl glorious dress for occasional wear ", description: "A lightweight, usually knitted, pullover dress, close-fitting and with a round neckline and short sleeves, worn as outer garment." , price: 533, stock: 3, category: "Kid", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725371722/Little-Girls-Fur-Jackets-Winter-Blue-Pink-Faux-Leather-with-Fur-Luxury-Clothes-Toddler-Elegant-Baby-Warm-Outerwear-2-3-4-5-7-9T_a1012b17-adeb-4668-bd6c-65589187a84a.2065c3cd9b94bd1490feb5dcb77f88bc_pxzf9f.jpg" },
    { name: "girl glorious dress for occasional wear ", description: "A lightweight, usually knitted, pullover dress, close-fitting and with a round neckline and short sleeves, worn as outer garment." , price: 300, stock: 2, category: "Kid", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725371721/a1f95ad61a820ad03ca24bcad205383a_apob3t.jpg" },
    { name: "girl glorious dress for occasional wear ", description: "A lightweight, usually knitted, pullover dress, close-fitting and with a round neckline and short sleeves, worn as outer garment." , price: 400, stock: 5, category: "Kid", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725371617/DSC01114BG_RBE8_15__65325_nnglef.jpg" },
    { name: "girl glorious dress for occasional wear ", description: "A lightweight, usually knitted, pullover dress, close-fitting and with a round neckline and short sleeves, worn as outer garment." , price: 405, stock: 6, category: "Kid", imageUrl: "" },
    
    { name: "girl glorious dress for occasional wear ", description: "A lightweight, usually knitted, pullover dress, close-fitting and with a round neckline and short sleeves, worn as outer garment." , price: 500, stock: 7, category: "Kid", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725371618/Abckids-Custom-Wholesale-Big-Kids-Wear-Vendor-Summer-Children-Girl-Clothing-Kids-Clothes-Flower-Girls-Dress-with-Floral-Print_yxmzzx.webp" },
    { name: "girl glorious dress for occasional wear ", description: "A lightweight, usually knitted, pullover dress, close-fitting and with a round neckline and short sleeves, worn as outer garment." , price: 565, stock: 9, category: "Kid", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725371617/O1CN01bXhhj31ez1jFZBv6F__2583103941-0-cib_owyva2.jpg" },
    { name: "girl glorious dress for occasional wear ", description: "A lightweight, usually knitted, pullover dress, close-fitting and with a round neckline and short sleeves, worn as outer garment." , price: 544, stock: 1, category: "Kid", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725371604/kids-clothes-uk_2C-girls-clothes-uk_2C-girls-dresses-uk_2C-girls-party-dresses-uk_2C-baby-dresses-uk_2C-baby-girl-clothes-uk_2C-baby-girl-dresses-uk_2C-baby-girl-dresses-special-occasion-uk_bxgp1j.webp" },
    { name: "girl glorious dress for occasional wear ", description: "A lightweight, usually knitted, pullover dress, close-fitting and with a round neckline and short sleeves, worn as outer garment." , price: 580, stock: 8, category: "Kid", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725371602/H018f4d2ea7a64339b8c3b6403d888654T.jpg_640x640Q90.jpg__wpcvd7.webp" },
    { name: "girl glorious dress for occasional wear ", description: "A lightweight, usually knitted, pullover dress, close-fitting and with a round neckline and short sleeves, worn as outer garment." , price: 520, stock: 4, category: "Kid", imageUrl: "" },
    
    { name: "girl glorious dress for occasional wear ", description: "A lightweight, usually knitted, pullover dress, close-fitting and with a round neckline and short sleeves, worn as outer garment." , price: 520, stock: 4, category: "Kid", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725371601/3a9f8496-1418-4305-8f4f-d58c33d2c856.e3ed444397b67d549dcfb0ef2fd2b0bc_co6jdn.jpg" },
    
    { name: "girl glorious dress for occasional wear ", description: "A lightweight, usually knitted, pullover dress, close-fitting and with a round neckline and short sleeves, worn as outer garment." , price: 520, stock: 4, category: "Kid", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725371601/ANNIESEQUINSHORTSLEEVEKIDSDRESS-KIDSDRESS-SKYPINK-NEEDLE_THREAD-6_uvnf45.jpg" },
    { name: "girl glorious dress for occasional wear ", description: "A lightweight, usually knitted, pullover dress, close-fitting and with a round neckline and short sleeves, worn as outer garment." , price: 520, stock: 4, category: "Kid", imageUrl: "https://res.cloudinary.com/dtcogqxhp/image/upload/v1725371601/s-l1200_zef0gg.jpg" },
     
    
];

db.serialize(() => {
    const stmt = db.prepare("INSERT INTO products (name, description, price, stock, category, imageUrl) VALUES (?, ?, ?, ?, ?, ?)");

    products.forEach(product => {
        stmt.run(product.name, product.description, product.price, product.stock, product.category, product.imageUrl);
    });

    stmt.finalize();
    console.log('20 products inserted successfully');
});




// Close the database connection (optional here, but good practice)
db.close();
